name: tools

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle:/data
    ports:
      - 8080
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_AUTH_PROVIDER=simple
    secrets:
      - source: users
        target: /data/users.yml
    restart: unless-stopped
    networks:
      - tools
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

secrets:
  users:
    file: users.yml
    # file: .local.users.yml

volumes:
  dozzle:

networks:
  tools:
    name: tools
    external: true
