services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    env_file:
      - ../docker.env
    volumes:
      - /config/overseerr:/app/config
    restart: unless-stopped
    networks:
      - daimo-dc

networks:
  daimo-dc:
    name: daimo-dc