name: multimedia

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - ../docker.env
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${HOME}/.config/qbittorrent:/config
      - /media/Data/@media:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia
    external: true
