
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - ../docker.env
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /config/qbittorrent:/config
      - /media/Data/media-data:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - daimo-dc

networks:
  daimo-dc:
    name: daimo-dc
    external: true
