name: multimedia

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file:
      - ../docker.env
    volumes:
      - /config/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia
    external: true
