name: multimedia

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Asia/Ho_Chi_Minh
    user: 1000:1000
    volumes:
      - ${HOME}/.config/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia
    external: true
