services:
  caddy:
    build: ./caddy
    restart: unless-stopped
    env_file:
      - ./caddy/caddy.env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/home/haitv/my-server/caddy
    extra_hosts:
    - "host.docker.internal:host-gateway"
  
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:0
    network_mode: 'host'
    volumes:
      - /config:/config
      - /media/Data/media:/media
    restart: 'unless-stopped'

volumes:
  caddy_data:
  caddy_config:
