services:
  caddy:
    build: ./caddy
    restart: unless-stopped
    env_file:
      - ./caddy/caddy.env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/home/haitv/my-server/caddy
    extra_hosts:
    - "host.docker.internal:host-gateway"
  
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /config/jellyfin:/config
      - /media/Data/media-data/media:/media
    restart: 'unless-stopped'

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /config/radarr:/config
      - /media/Data/media-data:/data
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /config/sonarr:/config
      - /media/Data/media-data:/data
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /config/bazarr:/config
      - /media/Data/media-data:/data
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /config/nzbget:/config
      - /media/Data/media-data/usenet:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
