name: Decode Environment files by SOPS
description: 'Decode .env files'

inputs:
  filePath:
    description: 'The name of the encoded file'
    required: true
    default: '.env'

runs:
  using: composite
  steps:
    - name: Setup Age Key
      shell: bash
      run: |
        AGE_KEY_FILE="/var/lib/github-runner/age-key.txt"
        if [[ -f "$AGE_KEY_FILE" ]]; then
          echo "SOPS_AGE_KEY_FILE=$AGE_KEY_FILE" >> "$GITHUB_ENV"
        else
          echo "::error::Age key file not found at $AGE_KEY_FILE"
          exit 1
        fi

    - name: Decrypt with SOPS
      shell: bash
      run: |
        sops -d -i -- ${{ inputs.filePath }}
