name: Decode Environment files by SOPS 

inputs:
  filePath:
    description: 'The name of the encoded file'
    required: true
    default: '.env'

runs:
  using: composite
  steps:
    - name: Import GPG Key from Local File
      shell: bash
      run: |
        GPG_KEY_FILE="/var/lib/github-runner/gpg-key.b64"
        if [[ -f "$GPG_KEY_FILE" ]]; then
          cat "$GPG_KEY_FILE" | base64 -d | gpg --import --quiet --no-tty
          gpg --list-secret-keys
        else
          echo "Warning: GPG key file not found at $GPG_KEY_FILE, SOPS may fail if decryption is needed"
        fi

    - name: SOPS
      shell: bash {0}
      run: |
        sops -d -i -- ${{ inputs.filePath }}
