name: Decode Environment files by SOPS 

inputs:
  fileName:
    description: 'The name of the encoded file'
    required: true
    default: '.env'
  gpgKey:
    description: 'The GPG private key'
    required: true
    default: ''

runs:
  using: composite
  steps:
    # - name: Configure GPG Key
    #   env:
    #     GPG_SIGNING_KEY: ${{ inputs.gpgKey }}
    #   shell: bash
    #   run: |
    #     echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
    #     gpg --list-secret-keys

    - name: SOPS
      shell: bash {0}
      run: |
        sh -c "echo 'Hello, host!' && whoami"
        sh -c "sops -d -i -- $${{ inputs.fileName }}"
