name: Decode Environment files by SOPS 

inputs:
  fileName:
    description: 'The name of the encoded file'
    required: true
    default: '.env'
  gpgKey:
    description: 'The GPG private key'
    required: true
    default: ''

run:
  using: "composite"
  steps:
    - name: Configure GPG Key
      env:
        GPG_SIGNING_KEY: ${{ inputs.gpgKey }}
      run: |
        echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        gpg --list-secret-keys

    - name: SOPS
      shell: bash {0}
      run: |
        sops -d -i -- ${{ inputs.fileName }}
