name: Decode Environment files by SOPS
description: 'Decode .env files'

inputs:
  filePath:
    description: 'The name of the encoded file'
    required: true
    default: '.env'
  ageKey:
    description: 'Age private key for SOPS decryption'
    required: true

runs:
  using: composite
  steps:
    - name: Decrypt with SOPS
      shell: bash
      env:
        SOPS_AGE_KEY: ${{ inputs.ageKey }}
      run: |
        sops -d -i -- ${{ inputs.filePath }}
