services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - ../docker.env
      - transmission/transmission.env
    volumes:
      - /config/transmission:/config
      - /media/Data/media-data/torrents:/data/torrents
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
