version: '3.8'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - ../docker.env
      - config.env
    volumes:
      - /config/transmission:/config
      - /media/Data/media-data/torrents:/data/torrents
    ports:
      - 9091
      - 51413
    restart: unless-stopped
    networks:
      - daimo-dc

networks:
  daimo-dc:
    name: daimo-dc
