name: tools

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - 8080 # webapp
      - 8086 # influxDB admin
    env_file:
      - ../docker.env
    volumes:
      - /run/udev:/run/udev:ro
      - ${HOME}/.config/scrutiny:/opt/scrutiny/config
      - ${HOME}/.config/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
      - "/dev/nvme0"
    restart: unless-stopped
    networks:
      - tools

networks:
  tools:
    name: tools
    external: true
