
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/garymathews/frigate:latest-rocm-7.2.3

    devices:
      - /dev/dri:/dev/dri # Required for hardware rendering & transcoding (VA-API)
      - /dev/kfd:/dev/kfd # Required for ROCm compute (e.g., machine learning, Ollama)

    environment:
      - HSA_OVERRIDE_GFX_VERSION=9.0.0
      - HSA_XNACK=0 # specify for gfx90c
      # Critical for GCN5 APUs to stop memory management crashes
      - HSA_USE_SVM=0
      # --- THE MEMORY SAVER TRICKS ---
      # Disable direct memory access restrictions to allow host memory fallback
      - HSA_ENABLE_SDMA=0
      # Force host-to-device memory coherence so APU compute can safely use system RAM chunks
      - HIP_HOST_COHERENT=1
      # Prevent ONNX Runtime from aggressively pre-allocating massive memory arenas
      - ORT_TENSORRT_ENGINE_CACHE_ENABLE=0

    shm_size: "256mb"

    volumes:
      - /home/haitv/.config/frigate:/config
      - /media/Data/@media/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # 1GB In-memory filesystem for recording segment storage
        target: /tmp/cache
        tmpfs:
          size: 1073741824

    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
      - "8971:8971/tcp"
      - "8971:8971/udp"
      - "1984:1984"
