name: Deploy to My Server

inputs:
  servicePath:
    description: 'The path of the deploy service'
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Deploy
      id: deploy
      shell: bash {0}
      run: |
        cd ${{ inputs.servicePath }}
        docker compose down
        docker compose up -d --build
