name: immich

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - ../docker.env
      - pgadmin.env
      - path: .pgadmin.local.env
        required: false
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - daimo-dc

networks:
  daimo-dc:
    name: daimo-dc
    external: true

volumes:
  pgadmin-data: