services:
  glances:
    container_name: glances
    image: nicolargo/glances:ubuntu-latest-full
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w --password"
    # For nvidia GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    secrets:
      - source: glances_password
        target: /root/.config/glances/glances.pwd
    networks:
      - daimo-dc

secrets:
  glances_password:
    file: /home/haitv/.config/glances/glances_password

networks:
  daimo-dc:
    name: daimo-dc