name: webserver

services:
  glances:
    container_name: glances
    image: nicolargo/glances:ubuntu-latest-full
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      - /etc/os-release:/etc/os-release:ro
      - /home/haitv/.config/glances/glances.conf:/etc/glances/glances.conf
      - /media/Data:/Data:ro
      - /root:/Root:ro
      - /home:/Home:ro
      - /media/BackupDisk:/BackupDisk:ro
    environment:
      - "GLANCES_OPT=-w --password"
    # For nvidia GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities:
                - gpu
    restart: unless-stopped
    secrets:
      - source: glances_password
        target: /root/.config/glances/glances.pwd
    network_mode: host

secrets:
  glances_password:
    file: /home/haitv/.config/glances/glances_password
