name: tools

services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../docker.env
      - config.env
      - path: .local.env
        required: false
    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - 3000
    restart: unless-stopped
    networks:
      - tools
    labels:
      - wud.trigger.exclude=docker.updater

networks:
  tools:
    name: tools
    external: true
