name: webserver

services:
  uptime-kuma:
    image: louislam/uptime-kuma:beta
    container_name: uptime-kuma
    user: 1000:1000
    volumes:
      - ${HOME}/.config/uptime-kuma:/app/data
    ports:
      - 3001
    restart: unless-stopped
    networks:
      - webserver

networks:
  webserver:
    name: webserver
    external: true
