name: webserver

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /config/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001
    restart: unless-stopped
    networks:
      - webserver

networks:
  webserver:
    name: webserver
    external: true
