name: multimedia

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - ../docker.env
    volumes:
      - /config/radarr:/config
      - /media/Data/@media:/data
    restart: unless-stopped
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia
    external: true
