name: multimedia

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - ../docker.env
    volumes:
      - /home/haitv/.config/sonarr:/config
      - /media/Data/@media:/data
    restart: unless-stopped
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia
    external: true
