name: multimedia

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - ../docker.env
    volumes:
      - ${HOME}/.config/sonarr:/config
      - /media/Data/@media:/data
    restart: unless-stopped
    networks:
      - daimo-dc

networks:
  daimo-dc:
    name: daimo-dc
    external: true
