name: Checkout and prepare

inputs:
  serviceName:
    description: 'The name of the service'
    required: true

env:
  MACHINE: daimo-dc

run:
  using: 'composite'
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: List files in the repository
      env:
        serviceName: ${{ inputs.serviceName }}
      run: |
        cd services/$serviceName
        ls ${{ github.workspace }}

    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
