name: Checkout and prepare

inputs:
  service_name:
    description: 'The name of the service'
    required: true

env:
  MACHINE: daimo-dc

run:
  using: "composite"
  steps:
    - name: List files in the repository
      env:
        service_name: ${{ inputs.service_name }}
      shell: bash
      run: |
        cd services/${{ inputs.service_name }}
        ls ${{ github.workspace }}
