name: Checkout and prepare

inputs:
  serviceName:
    description: 'The name of the service'
    required: true

env:
  MACHINE: daimo-dc

runs:
  using: composite
  steps:
    - name: List files in the repository
      shell: bash
      run: |
        cd services/${{ inputs.serviceName }}
        ls .
