name: multimedia

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - ../docker.env
    volumes:
      - ${HOME}/.config/prowlarr:/config
    restart: unless-stopped
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia
    external: true
