services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: 'host'
    env_file:
      - ../docker.env
    volumes:
      - /config/prowlarr:/config
    restart: unless-stopped