services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - ../docker.env
    volumes:
      - /config/prowlarr:/config
    restart: unless-stopped
    networks:
      - daimo-dc

networks:
  daimo-dc:
    name: daimo-dc
    external: true
