services:
  windows:
    image: dockurr/windows
    container_name: windows11
    privileged: true

    environment:
      VERSION: "11l"
      TZ: "Asia/Bangkok"
      RAM_SIZE: "4G"
      CPU_MODEL: "host"
      CPU_CORES: "2"
      DISK_SIZE: "64G"

      # GPU_PCI_IDS: "0000:01:00.0,0000:01:00.1"
      # GPU_DRIVER: "vfio"
      # GPU_PRIMARY: "true"
      # DISPLAY: "none"

      # MACHINE: "q35"
      # UEFI: "true"
      # HYPERVISOR: "false"

    devices:
      - /dev/kvm
      # - /dev/vfio/vfio
      # - /dev/vfio/0

    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"

    stop_grace_period: 2m

    volumes:
      - /media/Data/@vm/windows/11:/storage
