services:
  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    ports:
      - 2368
    env_file:
      - ../docker.env
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ${DB_USERNAME}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_DATABASE_NAME}
      url: https://blog.haivita.top
    volumes:
      - /config/ghost:/var/lib/ghost/content
    networks:
      - webserver

  ghost-db:
    image: mysql:8.0
    container_name: ghost-db
    restart: unless-stopped
    env_file:
      - ../docker.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - webserver

volumes:
  ghost:
  db:

networks:
  webserver:
    name: webserver
    external: true
