services:
  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    ports:
      - 2368
    user: 1000:100
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ${DB_USERNAME}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_DATABASE_NAME}
      security__staffDeviceVerification: false
      url: https://blog.haivita.top
    volumes:
      - ${HOME}/.config/ghost/content:/var/lib/ghost/content
    networks:
      - webserver

  ghost-db:
    image: mysql:8.0
    container_name: ghost-db
    restart: unless-stopped
    user: 1000:100
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${HOME}/.config/ghost/db:/var/lib/mysql
    networks:
      - webserver
    labels:
      - wud.watch=false

networks:
  webserver:
    name: webserver
    external: true
