
services:
  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    ports:
      - 2368
    env_file:
      - ../docker.env
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${DB_USERNAME}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_DATABASE_NAME}
      url: https://blog.haivita.dynv6.net
    volumes:
      - /config/ghost:/var/lib/ghost/content
    networks:
      - daimo-dc

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - ../docker.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - daimo-dc

volumes:
  ghost:
  db:

networks:
  daimo-dc:
    name: daimo-dc