services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    env_file:
      - ../docker.env
    user: 1000:1000
    volumes:
      - /media/Data:/srv
      - /config/filebrowser/database.db:/database/filebrowser.db
      - /config/filebrowser/settings.json:/.filebrowser.json
    restart: unless-stopped
    networks:
      - daimo-dc

networks:
  daimo-dc:
    name: daimo-dc