name: tools

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    volumes:
      - /media/Data:/srv
      - ${HOME}/.config/filebrowser:/database
      - ${HOME}/.config/filebrowser:/config
    restart: unless-stopped
    networks:
      - tools

networks:
  tools:
    name: tools
    external: true
