name: Deploy to My Server

run-name: ${{ github.actor }} is deploying to My Server 🚀

on:
  workflow_call:
    inputs:
      serviceName:
        description: 'The name of the service'
        required: true

env:
  MACHINE: daimo-dc

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          cd services/${{ inputs.serviceName | tr '[:lower:]' }}
          ls ${{ github.workspace }}

      - name: Setup & encode SOPS
        uses: .github/workflows/sops-decode.yml
        with:
          fileName: ${{ inputs.serviceName | tr '[:lower:]' }}.env

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Add SSH key
        id: ssh
        shell: bash {0}
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          MACHINE_IP="$(tailscale ip -6 $MACHINE)"
          ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
          printf "%s" "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key

      - name: Copy and Deploy
        id: deploy
        shell: bash {0}
        run: |
          TIME=$(date +%Y%m%d-%H%M%S)
          MACHINE_IP="$(tailscale ip -6 $MACHINE)"
          ssh -i ~/.ssh/key "haitv@$MACHINE_IP" "rm -rf ~/my-server;"
          GLOBIGNORE=".git:.github:README.md" scp -i ~/.ssh/key -r ${{ github.workspace }} "haitv@[$MACHINE_IP]://home/haitv/"
          ssh -i ~/.ssh/key "haitv@$MACHINE_IP" "cd ~/my-server;docker compose down;docker compose up -d;"
