env:
  SERVICE_PATH: services/homepage

name: Deploy HomePage to My Server

run-name: ${{ github.actor }} is deploying to My Server 🚀

on:
  push:
    branches:
      - main
    paths:
      - .gitmodules
      - services/homepage
      - services/homepage/**
      - .github/workflows/homepage.yml
      - .github/actions/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup & encode SOPS
        uses: ./.github/actions/sops-decode
        with:
          filePath: ${{ env.SERVICE_PATH }}/config.env

      - name: Deploy configs via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H haivita.top >> ~/.ssh/known_hosts
          rsync -avz --delete "${{ env.SERVICE_PATH }}/configs/" "${{ secrets.SSH_USERNAME }}@haivita.top:/home/haitv/homepage/configs/"

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          servicePath: ${{ env.SERVICE_PATH }}
