env:
  SERVICE_PATH: services/homepage

name: Deploy HomePage to My Server

run-name: ${{ github.actor }} is deploying to My Server 🚀

on:
  push:
    branches:
      - main
    paths:
      - services/homepage/**
      - .github/workflows/homepage.yml
      - .github/actions/**

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Sync Configs
        shell: bash {0}
        run: |
          rsync -avz --exclude={'.git','README.md'} ./${{ env.SERVICE_PATH }}/configs ~/homepage

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          servicePath: ${{ env.SERVICE_PATH }}
