env:
  SERVICE_PATH: services/homepage

name: Deploy HomePage to My Server

run-name: ${{ github.actor }} is deploying to My Server 🚀

on:
  push:
    branches:
      - main
    paths:
      - .gitmodules
      - services/homepage
      - services/homepage/**
      - .github/workflows/homepage.yml
      - .github/actions/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup & encode SOPS
        uses: ./.github/actions/sops-decode
        with:
          filePath: ${{ env.SERVICE_PATH }}/config.env

      - name: Deploy configs via SSH
        uses: appleboy/scp-action@master
        with:
          host: haivita.top
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "${{ env.SERVICE_PATH }}/configs/"
          target: "/home/haitv/homepage/configs"
          rm: true

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          servicePath: ${{ env.SERVICE_PATH }}
