env:
  SERVICE_PATH: services/ollama

name: Deploy Ollama to My Server

run-name: ${{ github.actor }} is deploying to My Server 🚀

on:
  push:
    branches:
      - main
    paths:
      - services/ollama/**
      - .github/workflows/ollama.yml
      - .github/actions/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          servicePath: ${{ env.SERVICE_PATH }}
